print("Hello, World!")
print("My favourite color is yellow.")
name = input("What is your name? ")
print(f'Hello {name}!')
age = input("How old are you? ")
print(f'{name} You look quite young for your age')